[project]
name = 'platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.contract-registry]
path = 'contracts/contract-registry.clar'
clarity_version = 3
epoch = 3.0

[contracts.expert-verification]
path = 'contracts/expert-verification.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
